name: run main.py

# on:
#   schedule:
#     - cron: '0 0 * * 6'

on:
  push:
    branches:
      - dev

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable 
    
      - name: Install dependencies and configure ChromeDriver
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay beautifulsoup4
          # wget https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          # unzip chromedriver_linux64.zip -d /tmp
          # mv /tmp/chromedriver /usr/local/bin/chromedriver
          # chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium script
        run: python main.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v2
        with:
          name: hdlscrapdata
          path: hdlscrapdata.csv